plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

// Vincula este cargador con su correspondiente módulo common
loader {
    common = ':fidgetz:common'
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-$parchment_minecraft:$parchment_version@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"
}

loom {
    // Usamos el mod_id definido en las propiedades globales
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("fidgetz.refmap.json")
    }
    runs {
        // En subproyectos de librería solemos quitar las ejecuciones 
        // para no duplicar los botones de "Run" en el IDE
        remove client
        remove server
    }
}
