# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.6
loader_version=0.16.14
parchment_minecraft=1.21.5
parchment_version=2025.04.19

# Mod Properties
mod_version=2.0.0+1.21.6
maven_group=io.github.fishstiz
archives_base_name=packed_packs
mod_name=Packed Packs

# Dependencies
fabric_api_version=0.127.0+1.21.6
modmenu_version=15.0.0-beta.1
mccursor_version=3.11.1+1.21.6
resourcify_version=Z1VzYmwk
respackopts_version=4.13.3
libjf_version=3.18.7
