# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
loader_version=0.16.10
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Mod Properties
mod_version=1.1.0-beta.1+1.21.1
maven_group=io.github.fishstiz
archives_base_name=packed_packs
mod_name=Packed Packs

# Dependencies
fabric_api_version=0.115.1+1.21.1
modmenu_version=11.0.3
mccursor_version=3.9.1+1.21.1
resourcify_version=bmmMRetc
respackopts_version=4.11.3
libjf_version=3.17.3
