# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Project
archives_base_name=packed_packs
maven_group=io.github.fishstiz
mod_version=2.0.4+1.20.1
mod_id=packed_packs
mod_name=Packed Packs
mod_author=fishstiz
mod_description=Pack packs into profiles with multiple selection, drag and drop, and extended mouse and keyboard controls.
java_version=17
license=MIT
sources=https://github.com/fishstiz/packed_packs
issues=https://github.com/fishstiz/packed_packs/issues
credits=StarmanMine142, iceban
minecraft_version=1.20.1
modrinth_id=8Pq6Exn2
curseforge_id=1260514

# Common
moddev_version=2.0.107
neo_form_version=1.20.1-20230612.114412
parchment_minecraft=1.20.1
parchment_version=2023.09.03
mixin_version=0.8.5
mixinextras_version=0.3.5
mod_publish_version=0.8.4
minecraft_cursor_version=1.1.4+1.20.1
resourcify_version=1.3.0
respackopts_version=4.3.0
libjf_resource_pack_entry_widgets_version=3.0.0

# Fabric
loom_version=1.7-SNAPSHOT
fabric_loader_version=0.15.11
fabric_api_version=0.92.2+1.20.1
fabric_minecraft_version_range=1.20.1
modmenu_version=7.2.2

# NeoForge (Mantenido por estructura, pero desactivado en settings)
neoforge_loader_version_range=[4,)
neoforge_version=47.1.0
neoforge_version_range=[47.1.0,)
neoforge_minecraft_version_range=[1.20.1]
