subprojects {
    if (project.name != "common") {
        afterEvaluate {
            apply plugin: 'multiloader-common'

            configurations {
                commonJava {
                    canBeResolved = true
                }
                commonResources {
                    canBeResolved = true
                }
            }

            dependencies {
                compileOnly project(path: ":fidgetz:common")
                commonJava project(path: ":fidgetz:common", configuration: "commonJava")
                commonResources project(path: ":fidgetz:common", configuration: "commonResources")
            }

            compileJava {
                dependsOn(configurations.commonJava)
                source(configurations.commonJava)
            }

            processResources {
                dependsOn(configurations.commonResources)
                from(configurations.commonResources)
            }

            sourcesJar {
                dependsOn(configurations.commonJava)
                from(configurations.commonJava)
                dependsOn(configurations.commonResources)
                from(configurations.commonResources)
            }
        }
    }
}
