plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

loader {
    common = ':fidgetz:common'
}

repositories {
    maven {
        name = "Maven for PR #2815" // https://github.com/neoforged/NeoForge/pull/2815
        url = uri("https://prmaven.neoforged.net/NeoForge/pr2815")
        content {
            includeModule("net.neoforged", "neoforge")
            includeModule("net.neoforged", "testframework")
        }
    }
}

neoForge {
    version = neoforge_version

    def at = project(loader.common).file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}
