plugins {
    id 'multiloader-common-provider'
    id 'java-library'
}

repositories {
    maven { url = "https://raw.githubusercontent.com/fishstiz/maven/m2" }
    maven { url = "https://maven.frohnmeyer-wds.de/artifacts" }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    // Referencia al common de la sub-librería
    compileOnlyApi project(path: ":fidgetz:common")

    compileOnly group: 'org.spongepowered', name: 'mixin', version: "$mixin_version"
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: "$mixinextras_version"
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: "$mixinextras_version"

    compileOnly "io.github.fishstiz:minecraft-cursor-common-api:$minecraft_cursor_version"
    compileOnly "maven.modrinth:resourcify:$resourcify_version"
    compileOnly "maven.modrinth:respackopts:$respackopts_version"
    // Nota: Aunque diga forge al final, si es una librería common se mantiene para compilación
    compileOnly "io.gitlab.jfronny.libjf:libjf-resource-pack-entry-widgets-forge:$libjf_resource_pack_entry_widgets_version"
}
